2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Configure stats pid to 47295
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Loading settings from /Users/simonmenzi/.config/wandb/settings
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Loading settings from /Users/simonmenzi/Developer/Private/NEM-MCMC-optimization/wandb/settings
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'experiments.py', 'program_abspath': '/Users/simonmenzi/Developer/Private/NEM-MCMC-optimization/experiments.py', 'program': '/Users/simonmenzi/Developer/Private/NEM-MCMC-optimization/experiments.py'}
2024-02-24 14:54:25,112 INFO    MainThread:47295 [wandb_init.py:_log_setup():526] Logging user logs to /Users/simonmenzi/Developer/Private/NEM-MCMC-optimization/wandb/run-20240224_145425-txilurql/logs/debug.log
2024-02-24 14:54:25,113 INFO    MainThread:47295 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/simonmenzi/Developer/Private/NEM-MCMC-optimization/wandb/run-20240224_145425-txilurql/logs/debug-internal.log
2024-02-24 14:54:25,113 INFO    MainThread:47295 [wandb_init.py:init():566] calling init triggers
2024-02-24 14:54:25,113 INFO    MainThread:47295 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'network_nr': 1, 'num_s': 19, 'num_e': 570, 'adj_matrix': array([[0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'errors': array([0.05, 0.08])}
2024-02-24 14:54:25,113 INFO    MainThread:47295 [wandb_init.py:init():616] starting backend
2024-02-24 14:54:25,113 INFO    MainThread:47295 [wandb_init.py:init():620] setting up manager
2024-02-24 14:54:25,114 INFO    MainThread:47295 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-24 14:54:25,114 INFO    MainThread:47295 [wandb_init.py:init():628] backend started and connected
2024-02-24 14:54:25,117 INFO    MainThread:47295 [wandb_init.py:init():720] updated telemetry
2024-02-24 14:54:25,134 INFO    MainThread:47295 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-24 14:54:26,356 WARNING MainThread:47295 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/Users/simonmenzi/Library/Python/3.9/lib/python/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/simonmenzi/Library/Python/3.9/lib/python/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/Users/simonmenzi/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/simonmenzi/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/simonmenzi/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-02-24 14:54:28,719 WARNING MsgRouterThr:47295 [router.py:message_loop():77] message_loop has been closed
